In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

# Import API key
from api_keys import weather_api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

In [2]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=1500)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

614

In [3]:
# create a dataframe with cities from the random list generated
city_weather = pd.DataFrame(cities,columns=['City'])
city_weather.head()

        City
0  carnarvon
1      korla
2    qaanaaq
3      okato
4    kahului

In [4]:
# create and append empty columns to city_weather dataframe
city_weather['Lat'] = ''
city_weather['Lng'] = ''
city_weather['Max Temp'] = ''
city_weather['Humidity'] = ''
city_weather['Cloudiness'] = ''
city_weather['Wind Speed'] = ''
city_weather['Country'] = ''
city_weather['Date'] = ''

city_weather.head()

        City Lat Lng Max Temp Humidity Cloudiness Wind Speed Country Date
0  carnarvon
1      korla
2    qaanaaq
3      okato
4    kahului

In [5]:
base_url = "http://api.openweathermap.org/data/2.5/weather?"
query_url = f"{base_url}appid={weather_api_key}&q="

In [7]:
print(f'Beginning Data Retrieval')
print(f'-------------------------------------')

record = 0
set_count = 1

for index, row in city_weather.iterrows():
    
    record = record + 1

    
    city_name = row['City']
    
    weather_response = requests.get(query_url + city_name)
    weather_json = weather_response.json()
    
    
    try:
        print(f"Processing Record {record} of Set {set_count} | {city_name}")
        
        city_weather.loc[index, 'Lat'] = weather_json['coord']['lat']
        city_weather.loc[index, 'Lng'] = weather_json['coord']['lon']
        city_weather.loc[index, 'Max Temp'] = weather_json['main']['temp_max']
        city_weather.loc[index, 'Humidity'] = weather_json['main']['humidity']
        city_weather.loc[index, 'Cloudiness'] = weather_json['clouds']['all']
        city_weather.loc[index, 'Wind Speed'] = weather_json['wind']['speed']
        city_weather.loc[index, 'Country'] = weather_json['sys']['country']
        city_weather.loc[index, 'Date'] = weather_json['dt']
        
    except (KeyError, IndexError):
        
        print(f'City not found. Skipping...')
    if record == 50:
        set_count = set_count+1
        record = 0

print(f'-------------------------------------')
print(f'Data Retrieval Complete')
print(f'-------------------------------------')

Beginning Data Retrieval
-------------------------------------
Processing Record 1 of Set 1 | carnarvon
Processing Record 2 of Set 1 | korla
Processing Record 3 of Set 1 | qaanaaq
Processing Record 4 of Set 1 | okato
Processing Record 5 of Set 1 | kahului
Processing Record 6 of Set 1 | kapaa
Processing Record 7 of Set 1 | arraial do cabo
Processing Record 8 of Set 1 | ushuaia
Processing Record 9 of Set 1 | saint george
Processing Record 10 of Set 1 | adrar
Processing Record 11 of Set 1 | jamestown
Processing Record 12 of Set 1 | saleaula
City not found. Skipping...
Processing Record 13 of Set 1 | avarua
Processing Record 14 of Set 1 | dikson
Processing Record 15 of Set 1 | hasaki
Processing Record 16 of Set 1 | norman wells
Processing Record 17 of Set 1 | mar del plata
Processing Record 18 of Set 1 | baykit
Processing Record 19 of Set 1 | kulu
Processing Record 20 of Set 1 | moscow
Processing Record 21 of Set 1 | kindu
Processing Record 22 of Set 1 | araouane
Processing Record 23 of Set 1 | clyde river
Processing Record 24 of Set 1 | barentsburg
City not found. Skipping...
Processing Record 25 of Set 1 | mataura
Processing Record 26 of Set 1 | haapsalu
Processing Record 27 of Set 1 | amderma
City not found. Skipping...
Processing Record 28 of Set 1 | shadegan
Processing Record 29 of Set 1 | nuristan
Processing Record 30 of Set 1 | beloha
Processing Record 31 of Set 1 | bargal
City not found. Skipping...
Processing Record 32 of Set 1 | rikitea
Processing Record 33 of Set 1 | lompoc
Processing Record 34 of Set 1 | neuquen
Processing Record 35 of Set 1 | provideniya
Processing Record 36 of Set 1 | ornskoldsvik
Processing Record 37 of Set 1 | butaritari
Processing Record 38 of Set 1 | middelkerke
Processing Record 39 of Set 1 | north bend
Processing Record 40 of Set 1 | caico
Processing Record 41 of Set 1 | paamiut
Processing Record 42 of Set 1 | atuona
Processing Record 43 of Set 1 | cherskiy
Processing Record 44 of Set 1 | mahebourg
Processing Record 45 of Set 1 | danielskuil
Processing Record 46 of Set 1 | grand river south east
City not found. Skipping...
Processing Record 47 of Set 1 | khatanga
Processing Record 48 of Set 1 | aksu
Processing Record 49 of Set 1 | taolanaro
City not found. Skipping...
Processing Record 50 of Set 1 | tasiilaq
Processing Record 1 of Set 2 | coahuayana
Processing Record 2 of Set 2 | talnakh
Processing Record 3 of Set 2 | hualmay
Processing Record 4 of Set 2 | rio gallegos
Processing Record 5 of Set 2 | umm durman
City not found. Skipping...
Processing Record 6 of Set 2 | kodiak
Processing Record 7 of Set 2 | jiblah
Processing Record 8 of Set 2 | la asuncion
Processing Record 9 of Set 2 | hobart
Processing Record 10 of Set 2 | druzhba
Processing Record 11 of Set 2 | victoria
Processing Record 12 of Set 2 | busselton
Processing Record 13 of Set 2 | saskylakh
Processing Record 14 of Set 2 | sao francisco de assis
Processing Record 15 of Set 2 | thompson
Processing Record 16 of Set 2 | kalmunai
Processing Record 17 of Set 2 | bolungarvik
City not found. Skipping...
Processing Record 18 of Set 2 | hanna
Processing Record 19 of Set 2 | bara
Processing Record 20 of Set 2 | barrow
Processing Record 21 of Set 2 | zyryanka
Processing Record 22 of Set 2 | matara
Processing Record 23 of Set 2 | tulun
Processing Record 24 of Set 2 | punta arenas
Processing Record 25 of Set 2 | kysyl-syr
Processing Record 26 of Set 2 | tuktoyaktuk
Processing Record 27 of Set 2 | new norfolk
Processing Record 28 of Set 2 | bambous virieux
Processing Record 29 of Set 2 | albany
Processing Record 30 of Set 2 | pevek
Processing Record 31 of Set 2 | cedar lake
Processing Record 32 of Set 2 | krk
Processing Record 33 of Set 2 | diapaga
Processing Record 34 of Set 2 | cap malheureux
Processing Record 35 of Set 2 | macaboboni
City not found. Skipping...
Processing Record 36 of Set 2 | puerto ayora
Processing Record 37 of Set 2 | castro
Processing Record 38 of Set 2 | navahrudak
Processing Record 39 of Set 2 | tuatapere
Processing Record 40 of Set 2 | naze
Processing Record 41 of Set 2 | mezen
Processing Record 42 of Set 2 | tete
Processing Record 43 of Set 2 | basyanovskiy
City not found. Skipping...
Processing Record 44 of Set 2 | saint-philippe
Processing Record 45 of Set 2 | fortuna
Processing Record 46 of Set 2 | nago
Processing Record 47 of Set 2 | truth or consequences
Processing Record 48 of Set 2 | aquiraz
Processing Record 49 of Set 2 | vaitupu
City not found. Skipping...
Processing Record 50 of Set 2 | charters towers
Processing Record 1 of Set 3 | owando
Processing Record 2 of Set 3 | lebu
Processing Record 3 of Set 3 | illoqqortoormiut
City not found. Skipping...
Processing Record 4 of Set 3 | hermanus
Processing Record 5 of Set 3 | aklavik
Processing Record 6 of Set 3 | nizhneyansk
City not found. Skipping...
Processing Record 7 of Set 3 | krasnoselkup
Processing Record 8 of Set 3 | karratha
Processing Record 9 of Set 3 | mys shmidta
City not found. Skipping...
Processing Record 10 of Set 3 | leh
Processing Record 11 of Set 3 | lolodorf
Processing Record 12 of Set 3 | darhan
Processing Record 13 of Set 3 | vaini
Processing Record 14 of Set 3 | chengde
Processing Record 15 of Set 3 | esperance
Processing Record 16 of Set 3 | angoram
Processing Record 17 of Set 3 | hilo
Processing Record 18 of Set 3 | vestmannaeyjar
Processing Record 19 of Set 3 | general roca
Processing Record 20 of Set 3 | cidreira
Processing Record 21 of Set 3 | ronchi dei legionari
Processing Record 22 of Set 3 | severo-kurilsk
Processing Record 23 of Set 3 | cabo san lucas
Processing Record 24 of Set 3 | fomboni
Processing Record 25 of Set 3 | gizo
Processing Record 26 of Set 3 | dubti
Processing Record 27 of Set 3 | nokaneng
Processing Record 28 of Set 3 | cape town
Processing Record 29 of Set 3 | al
City not found. Skipping...
Processing Record 30 of Set 3 | tiksi
Processing Record 31 of Set 3 | port elizabeth
Processing Record 32 of Set 3 | faanui
Processing Record 33 of Set 3 | port-gentil
Processing Record 34 of Set 3 | la palma
Processing Record 35 of Set 3 | santa vitoria do palmar
Processing Record 36 of Set 3 | doha
Processing Record 37 of Set 3 | fort-shevchenko
Processing Record 38 of Set 3 | mrirt
City not found. Skipping...
Processing Record 39 of Set 3 | torbay
Processing Record 40 of Set 3 | acapulco
Processing Record 41 of Set 3 | jijiga
Processing Record 42 of Set 3 | tsihombe
City not found. Skipping...
Processing Record 43 of Set 3 | cabinda
Processing Record 44 of Set 3 | pisco
Processing Record 45 of Set 3 | yulara
Processing Record 46 of Set 3 | hearst
Processing Record 47 of Set 3 | sur
Processing Record 48 of Set 3 | fatezh
Processing Record 49 of Set 3 | pangnirtung
Processing Record 50 of Set 3 | bluff
Processing Record 1 of Set 4 | sola
Processing Record 2 of Set 4 | baillif
Processing Record 3 of Set 4 | beringovskiy
Processing Record 4 of Set 4 | georgetown
Processing Record 5 of Set 4 | yuancheng
Processing Record 6 of Set 4 | nikolskoye
Processing Record 7 of Set 4 | ancud
Processing Record 8 of Set 4 | mount isa
Processing Record 9 of Set 4 | pacific grove
Processing Record 10 of Set 4 | gwanda
Processing Record 11 of Set 4 | bubaque
Processing Record 12 of Set 4 | richards bay
Processing Record 13 of Set 4 | yellowknife
Processing Record 14 of Set 4 | nelson bay
Processing Record 15 of Set 4 | kaitangata
Processing Record 16 of Set 4 | tilichiki
Processing Record 17 of Set 4 | araci
Processing Record 18 of Set 4 | byron bay
Processing Record 19 of Set 4 | kavieng
Processing Record 20 of Set 4 | henties bay
Processing Record 21 of Set 4 | mehamn
Processing Record 22 of Set 4 | oranjemund
Processing Record 23 of Set 4 | ribeira grande
Processing Record 24 of Set 4 | barcelos
Processing Record 25 of Set 4 | sitka
Processing Record 26 of Set 4 | shimabara
Processing Record 27 of Set 4 | banda aceh
Processing Record 28 of Set 4 | bredasdorp
Processing Record 29 of Set 4 | vallenar
Processing Record 30 of Set 4 | iquitos
Processing Record 31 of Set 4 | tidore
City not found. Skipping...
Processing Record 32 of Set 4 | sentyabrskiy
City not found. Skipping...
Processing Record 33 of Set 4 | coihaique
Processing Record 34 of Set 4 | airai
Processing Record 35 of Set 4 | puerto baquerizo moreno

Processing Record 36 of Set 4 | fairbanks
Processing Record 37 of Set 4 | ajdabiya
Processing Record 38 of Set 4 | samalaeulu
City not found. Skipping...
Processing Record 39 of Set 4 | bengkulu
Processing Record 40 of Set 4 | culipapa
City not found. Skipping...
Processing Record 41 of Set 4 | anadyr
Processing Record 42 of Set 4 | raipur
Processing Record 43 of Set 4 | colares
Processing Record 44 of Set 4 | tumannyy
City not found. Skipping...
Processing Record 45 of Set 4 | sibolga
Processing Record 46 of Set 4 | port alfred
Processing Record 47 of Set 4 | todos santos
Processing Record 48 of Set 4 | kayerkan
Processing Record 49 of Set 4 | chicama
Processing Record 50 of Set 4 | bathsheba
Processing Record 1 of Set 5 | namwala
Processing Record 2 of Set 5 | kencong
Processing Record 3 of Set 5 | sorsk
Processing Record 4 of Set 5 | leningradskiy
Processing Record 5 of Set 5 | ahipara
Processing Record 6 of Set 5 | santa cruz
Processing Record 7 of Set 5 | geraldton
Processing Record 8 of Set 5 | nome
Processing Record 9 of Set 5 | suleja
Processing Record 10 of Set 5 | laguna
Processing Record 11 of Set 5 | christchurch
Processing Record 12 of Set 5 | attawapiskat
City not found. Skipping...
Processing Record 13 of Set 5 | shaowu
Processing Record 14 of Set 5 | progreso
Processing Record 15 of Set 5 | alyangula
Processing Record 16 of Set 5 | chirnogeni
Processing Record 17 of Set 5 | olinda
Processing Record 18 of Set 5 | chokurdakh
Processing Record 19 of Set 5 | longyearbyen
Processing Record 20 of Set 5 | marrakesh
Processing Record 21 of Set 5 | guasdualito
Processing Record 22 of Set 5 | sinnamary
Processing Record 23 of Set 5 | kemijarvi
Processing Record 24 of Set 5 | caravelas
Processing Record 25 of Set 5 | dori
Processing Record 26 of Set 5 | padang
Processing Record 27 of Set 5 | upernavik
Processing Record 28 of Set 5 | north branch
Processing Record 29 of Set 5 | noumea
Processing Record 30 of Set 5 | luena
Processing Record 31 of Set 5 | touros
Processing Record 32 of Set 5 | haines junction
Processing Record 33 of Set 5 | asau
Processing Record 34 of Set 5 | port hedland
Processing Record 35 of Set 5 | saint-augustin
Processing Record 36 of Set 5 | belushya guba
City not found. Skipping...
Processing Record 37 of Set 5 | san policarpo
Processing Record 38 of Set 5 | port lincoln
Processing Record 39 of Set 5 | iqaluit
Processing Record 40 of Set 5 | okhotsk
Processing Record 41 of Set 5 | tempio pausania
Processing Record 42 of Set 5 | tabuk
Processing Record 43 of Set 5 | dunedin
Processing Record 44 of Set 5 | muroto
Processing Record 45 of Set 5 | dzemul
Processing Record 46 of Set 5 | kavaratti
Processing Record 47 of Set 5 | koshurnikovo
Processing Record 48 of Set 5 | bilibino
Processing Record 49 of Set 5 | maceio
Processing Record 50 of Set 5 | sulurpeta
City not found. Skipping...
Processing Record 1 of Set 6 | badiraguato
Processing Record 2 of Set 6 | xiangfan
Processing Record 3 of Set 6 | yarada
Processing Record 4 of Set 6 | andenes
Processing Record 5 of Set 6 | mayo
Processing Record 6 of Set 6 | brae
Processing Record 7 of Set 6 | gubkinskiy
Processing Record 8 of Set 6 | xingcheng
Processing Record 9 of Set 6 | axim
Processing Record 10 of Set 6 | isangel
Processing Record 11 of Set 6 | thunder bay
Processing Record 12 of Set 6 | teknaf
Processing Record 13 of Set 6 | east london
Processing Record 14 of Set 6 | porbandar
Processing Record 15 of Set 6 | coquimbo
Processing Record 16 of Set 6 | lata
Processing Record 17 of Set 6 | alice springs
Processing Record 18 of Set 6 | ekibastuz
Processing Record 19 of Set 6 | canico
Processing Record 20 of Set 6 | abu zabad
Processing Record 21 of Set 6 | san quintin
Processing Record 22 of Set 6 | mount darwin
Processing Record 23 of Set 6 | ajaccio
Processing Record 24 of Set 6 | panlaitan
Processing Record 25 of Set 6 | ende
Processing Record 26 of Set 6 | margate
Processing Record 27 of Set 6 | trairi
Processing Record 28 of Set 6 | bay roberts
Processing Record 29 of Set 6 | kathmandu
Processing Record 30 of Set 6 | beinamar
Processing Record 31 of Set 6 | yining
Processing Record 32 of Set 6 | cortez
Processing Record 33 of Set 6 | stepnyak
Processing Record 34 of Set 6 | parnu-jaagupi
Processing Record 35 of Set 6 | grindavik
Processing Record 36 of Set 6 | jati
Processing Record 37 of Set 6 | algiers
Processing Record 38 of Set 6 | japura
Processing Record 39 of Set 6 | kruisfontein
Processing Record 40 of Set 6 | verdalsora
City not found. Skipping...
Processing Record 41 of Set 6 | lodwar
Processing Record 42 of Set 6 | whitehorse
Processing Record 43 of Set 6 | bethel
Processing Record 44 of Set 6 | ixtapa
Processing Record 45 of Set 6 | manikling
Processing Record 46 of Set 6 | baruun-urt
Processing Record 47 of Set 6 | hihifo
City not found. Skipping...
Processing Record 48 of Set 6 | bardiyah
Processing Record 49 of Set 6 | rapid valley
Processing Record 50 of Set 6 | gueret
Processing Record 1 of Set 7 | porto walter
Processing Record 2 of Set 7 | makat
Processing Record 3 of Set 7 | nata
Processing Record 4 of Set 7 | taoudenni
Processing Record 5 of Set 7 | shakiso
Processing Record 6 of Set 7 | orlik
Processing Record 7 of Set 7 | sterling
Processing Record 8 of Set 7 | butembo
Processing Record 9 of Set 7 | vanimo
Processing Record 10 of Set 7 | constitucion
Processing Record 11 of Set 7 | harper
Processing Record 12 of Set 7 | kasongo-lunda
Processing Record 13 of Set 7 | santiago del estero
Processing Record 14 of Set 7 | rurrenabaque
Processing Record 15 of Set 7 | pangai
Processing Record 16 of Set 7 | saint-ambroise
Processing Record 17 of Set 7 | magistralnyy
Processing Record 18 of Set 7 | palabuhanratu
City not found. Skipping...
Processing Record 19 of Set 7 | jalu
Processing Record 20 of Set 7 | prince rupert
Processing Record 21 of Set 7 | mayumba
Processing Record 22 of Set 7 | ponta do sol
Processing Record 23 of Set 7 | antibes
Processing Record 24 of Set 7 | san patricio
Processing Record 25 of Set 7 | valparaiso
Processing Record 26 of Set 7 | jiddah
City not found. Skipping...
Processing Record 27 of Set 7 | afua
Processing Record 28 of Set 7 | sao filipe
Processing Record 29 of Set 7 | souillac
Processing Record 30 of Set 7 | mount gambier
Processing Record 31 of Set 7 | hithadhoo
Processing Record 32 of Set 7 | velyka pysarivka
Processing Record 33 of Set 7 | qaqortoq
Processing Record 34 of Set 7 | galiwinku
City not found. Skipping...
Processing Record 35 of Set 7 | sarany
Processing Record 36 of Set 7 | hammerfest
Processing Record 37 of Set 7 | santa rosa
Processing Record 38 of Set 7 | zhoucheng
Processing Record 39 of Set 7 | mbala
Processing Record 40 of Set 7 | fort nelson
Processing Record 41 of Set 7 | coari
Processing Record 42 of Set 7 | surin
Processing Record 43 of Set 7 | mizdah
Processing Record 44 of Set 7 | rameshki
Processing Record 45 of Set 7 | buala
Processing Record 46 of Set 7 | codrington
Processing Record 47 of Set 7 | erie
Processing Record 48 of Set 7 | brigantine
Processing Record 49 of Set 7 | taltal
Processing Record 50 of Set 7 | penzance
Processing Record 1 of Set 8 | jishou
Processing Record 2 of Set 8 | aflu
City not found. Skipping...
Processing Record 3 of Set 8 | kolokani
Processing Record 4 of Set 8 | te anau
Processing Record 5 of Set 8 | shihezi
Processing Record 6 of Set 8 | sao joao da barra
Processing Record 7 of Set 8 | salalah
Processing Record 8 of Set 8 | viligili
City not found. Skipping...
Processing Record 9 of Set 8 | dauphin
Processing Record 10 of Set 8 | roma
Processing Record 11 of Set 8 | guymon
Processing Record 12 of Set 8 | presidencia roque saenz pena
Processing Record 13 of Set 8 | seoul
Processing Record 14 of Set 8 | hofn
Processing Record 15 of Set 8 | magway
Processing Record 16 of Set 8 | xinzhi
Processing Record 17 of Set 8 | novorozhdestvenskaya
Processing Record 18 of Set 8 | narsaq
Processing Record 19 of Set 8 | kenora
Processing Record 20 of Set 8 | lagoa
Processing Record 21 of Set 8 | guerrero negro
Processing Record 22 of Set 8 | arman
Processing Record 23 of Set 8 | dakar
Processing Record 24 of Set 8 | eldikan
City not found. Skipping...
Processing Record 25 of Set 8 | rawson
Processing Record 26 of Set 8 | ballina

Processing Record 27 of Set 8 | tsentralnyy
City not found. Skipping...
Processing Record 28 of Set 8 | ullapool
Processing Record 29 of Set 8 | makakilo city
Processing Record 30 of Set 8 | manavalakurichi
Processing Record 31 of Set 8 | bandraboua
Processing Record 32 of Set 8 | inuvik
Processing Record 33 of Set 8 | yeppoon
Processing Record 34 of Set 8 | faya
Processing Record 35 of Set 8 | madimba
Processing Record 36 of Set 8 | luau
Processing Record 37 of Set 8 | jabiru
City not found. Skipping...
Processing Record 38 of Set 8 | lewiston
Processing Record 39 of Set 8 | hamilton
Processing Record 40 of Set 8 | huarmey
Processing Record 41 of Set 8 | goderich
Processing Record 42 of Set 8 | ulaangom
Processing Record 43 of Set 8 | lefka
Processing Record 44 of Set 8 | gonaives
Processing Record 45 of Set 8 | marcona
City not found. Skipping...
Processing Record 46 of Set 8 | luderitz
Processing Record 47 of Set 8 | khani
Processing Record 48 of Set 8 | quatre cocos
Processing Record 49 of Set 8 | neuenburg
Processing Record 50 of Set 8 | naliya
Processing Record 1 of Set 9 | saint anthony
Processing Record 2 of Set 9 | kampong cham
Processing Record 3 of Set 9 | nantucket
Processing Record 4 of Set 9 | maltahohe
Processing Record 5 of Set 9 | hitoyoshi
Processing Record 6 of Set 9 | bac lieu
Processing Record 7 of Set 9 | chuy
Processing Record 8 of Set 9 | necochea
Processing Record 9 of Set 9 | melo
Processing Record 10 of Set 9 | bibiani
Processing Record 11 of Set 9 | chato
Processing Record 12 of Set 9 | bakel
Processing Record 13 of Set 9 | corpus christi
Processing Record 14 of Set 9 | veraval
Processing Record 15 of Set 9 | zlitan
Processing Record 16 of Set 9 | semnan
Processing Record 17 of Set 9 | namibe
Processing Record 18 of Set 9 | portland
Processing Record 19 of Set 9 | zaragoza
Processing Record 20 of Set 9 | klaksvik
Processing Record 21 of Set 9 | sistranda
Processing Record 22 of Set 9 | bethanien
Processing Record 23 of Set 9 | chagda
City not found. Skipping...
Processing Record 24 of Set 9 | pokhara
Processing Record 25 of Set 9 | sumbe
Processing Record 26 of Set 9 | kasane
Processing Record 27 of Set 9 | le port
Processing Record 28 of Set 9 | alcaniz
Processing Record 29 of Set 9 | thinadhoo
Processing Record 30 of Set 9 | san felipe
Processing Record 31 of Set 9 | havre-saint-pierre
Processing Record 32 of Set 9 | kozhevnikovo
Processing Record 33 of Set 9 | vila velha
Processing Record 34 of Set 9 | changli
Processing Record 35 of Set 9 | itarema
Processing Record 36 of Set 9 | volgograd
Processing Record 37 of Set 9 | buta
Processing Record 38 of Set 9 | tucuma
Processing Record 39 of Set 9 | muros
Processing Record 40 of Set 9 | alofi
Processing Record 41 of Set 9 | saquena
Processing Record 42 of Set 9 | bandarbeyla
Processing Record 43 of Set 9 | champerico
Processing Record 44 of Set 9 | chenghai
Processing Record 45 of Set 9 | pryazha
Processing Record 46 of Set 9 | ntoum
Processing Record 47 of Set 9 | lipin bor
Processing Record 48 of Set 9 | vao
Processing Record 49 of Set 9 | sale
Processing Record 50 of Set 9 | zaysan
Processing Record 1 of Set 10 | gainesville
Processing Record 2 of Set 10 | wembley
Processing Record 3 of Set 10 | luwuk
Processing Record 4 of Set 10 | bereda
Processing Record 5 of Set 10 | ambanja
Processing Record 6 of Set 10 | leku
Processing Record 7 of Set 10 | dwarka
Processing Record 8 of Set 10 | chifeng
Processing Record 9 of Set 10 | marawi
Processing Record 10 of Set 10 | juba
Processing Record 11 of Set 10 | aitape
Processing Record 12 of Set 10 | farafangana
Processing Record 13 of Set 10 | lebyazhye
Processing Record 14 of Set 10 | matamoros
Processing Record 15 of Set 10 | pital
Processing Record 16 of Set 10 | novyy urengoy
Processing Record 17 of Set 10 | poum
Processing Record 18 of Set 10 | sioux lookout
Processing Record 19 of Set 10 | high level
Processing Record 20 of Set 10 | cah ab
City not found. Skipping...
Processing Record 21 of Set 10 | broken hill
Processing Record 22 of Set 10 | ostrovnoy
Processing Record 23 of Set 10 | ndioum
Processing Record 24 of Set 10 | corowa
Processing Record 25 of Set 10 | businga
Processing Record 26 of Set 10 | zhigansk
Processing Record 27 of Set 10 | vila do maio
Processing Record 28 of Set 10 | nioki
Processing Record 29 of Set 10 | avera
Processing Record 30 of Set 10 | khilok
Processing Record 31 of Set 10 | finschhafen
Processing Record 32 of Set 10 | parole
Processing Record 33 of Set 10 | soubre
Processing Record 34 of Set 10 | roald
Processing Record 35 of Set 10 | dolbeau
City not found. Skipping...
Processing Record 36 of Set 10 | khandyga
Processing Record 37 of Set 10 | kantunilkin
Processing Record 38 of Set 10 | kirkuk
Processing Record 39 of Set 10 | gbarnga
Processing Record 40 of Set 10 | monte carmelo
Processing Record 41 of Set 10 | bonoua
Processing Record 42 of Set 10 | alta floresta
Processing Record 43 of Set 10 | sheregesh
Processing Record 44 of Set 10 | sao jose da coroa grande
Processing Record 45 of Set 10 | waingapu
Processing Record 46 of Set 10 | novo aripuana
Processing Record 47 of Set 10 | siocon
Processing Record 48 of Set 10 | beisfjord
Processing Record 49 of Set 10 | ola
Processing Record 50 of Set 10 | aden
Processing Record 1 of Set 11 | lakselv
Processing Record 2 of Set 11 | mocambique
City not found. Skipping...
Processing Record 3 of Set 11 | buraydah
Processing Record 4 of Set 11 | key west
Processing Record 5 of Set 11 | alekseyevsk
Processing Record 6 of Set 11 | markova
Processing Record 7 of Set 11 | meulaboh
Processing Record 8 of Set 11 | burgeo
Processing Record 9 of Set 11 | mercedes
Processing Record 10 of Set 11 | russell
Processing Record 11 of Set 11 | wilmington
Processing Record 12 of Set 11 | pottsville
Processing Record 13 of Set 11 | icod de los vinos
Processing Record 14 of Set 11 | ilulissat
Processing Record 15 of Set 11 | khor
Processing Record 16 of Set 11 | anyang
Processing Record 17 of Set 11 | atocha
Processing Record 18 of Set 11 | sept-iles
Processing Record 19 of Set 11 | namatanai
Processing Record 20 of Set 11 | sahrak
City not found. Skipping...
Processing Record 21 of Set 11 | griffith
Processing Record 22 of Set 11 | krasnyy chikoy
Processing Record 23 of Set 11 | cherepovets
Processing Record 24 of Set 11 | bowen
Processing Record 25 of Set 11 | mnogovershinnyy
Processing Record 26 of Set 11 | kaabong
Processing Record 27 of Set 11 | golden
Processing Record 28 of Set 11 | kikwit
Processing Record 29 of Set 11 | nara
Processing Record 30 of Set 11 | floro
Processing Record 31 of Set 11 | inderborskiy
City not found. Skipping...
Processing Record 32 of Set 11 | bull savanna
Processing Record 33 of Set 11 | leibnitz
Processing Record 34 of Set 11 | port moresby
Processing Record 35 of Set 11 | caconda
Processing Record 36 of Set 11 | patacamaya
Processing Record 37 of Set 11 | tabou
Processing Record 38 of Set 11 | dingle
Processing Record 39 of Set 11 | vardo
Processing Record 40 of Set 11 | yatou
Processing Record 41 of Set 11 | lindi
Processing Record 42 of Set 11 | beyneu
Processing Record 43 of Set 11 | mersing
Processing Record 44 of Set 11 | svetlogorsk
Processing Record 45 of Set 11 | manaquiri
Processing Record 46 of Set 11 | tazovskiy
Processing Record 47 of Set 11 | pavino
Processing Record 48 of Set 11 | belyy yar
Processing Record 49 of Set 11 | lufilufi
Processing Record 50 of Set 11 | praia
Processing Record 1 of Set 12 | porto novo
Processing Record 2 of Set 12 | soe
Processing Record 3 of Set 12 | puri
Processing Record 4 of Set 12 | suao
City not found. Skipping...
Processing Record 5 of Set 12 | rognan
Processing Record 6 of Set 12 | vila franca do campo
Processing Record 7 of Set 12 | auki
Processing Record 8 of Set 12 | okakarara
Processing Record 9 of Set 12 | la ronge
Processing Record 10 of Set 12 | wanlaweyn
Processing Record 11 of Set 12 | kadiri
Processing Record 12 of Set 12 | vilhena
Processing Record 13 of Set 12 | srandakan
Processing Record 14 of Set 12 | port augusta
Processing Record 15 of Set 12 | rock sound
Processing Record 16 of Set 12 | tiznit
Processing Record 17 of Set 12 | ushtobe
Processing Record 18 of Set 12 | kaka
Processing Record 19 of Set 12 | college

Processing Record 20 of Set 12 | blind river
Processing Record 21 of Set 12 | rocha
Processing Record 22 of Set 12 | cam pha
City not found. Skipping...
Processing Record 23 of Set 12 | ratnagiri
Processing Record 24 of Set 12 | nanortalik
Processing Record 25 of Set 12 | guider
Processing Record 26 of Set 12 | atambua
Processing Record 27 of Set 12 | the valley
Processing Record 28 of Set 12 | upington
Processing Record 29 of Set 12 | petropavlovsk-kamchatskiy
Processing Record 30 of Set 12 | yerbogachen
Processing Record 31 of Set 12 | jujuy
City not found. Skipping...
Processing Record 32 of Set 12 | birin
Processing Record 33 of Set 12 | olafsvik
Processing Record 34 of Set 12 | cruz alta
Processing Record 35 of Set 12 | kodinar
Processing Record 36 of Set 12 | parkersburg
Processing Record 37 of Set 12 | itacoatiara
Processing Record 38 of Set 12 | pagudpud
Processing Record 39 of Set 12 | maine-soroa
Processing Record 40 of Set 12 | broome
Processing Record 41 of Set 12 | black river
Processing Record 42 of Set 12 | brandon
Processing Record 43 of Set 12 | malabon
Processing Record 44 of Set 12 | comodoro rivadavia
Processing Record 45 of Set 12 | cayenne
Processing Record 46 of Set 12 | takoradi
Processing Record 47 of Set 12 | bireun
Processing Record 48 of Set 12 | neiafu
Processing Record 49 of Set 12 | awbari
Processing Record 50 of Set 12 | baghdad
Processing Record 1 of Set 13 | labuan
Processing Record 2 of Set 13 | ramacca
Processing Record 3 of Set 13 | egvekinot
Processing Record 4 of Set 13 | san andres
Processing Record 5 of Set 13 | ayan
Processing Record 6 of Set 13 | vostok
Processing Record 7 of Set 13 | galgani
City not found. Skipping...
Processing Record 8 of Set 13 | gornopravdinsk
Processing Record 9 of Set 13 | tazmalt
Processing Record 10 of Set 13 | borovoy
Processing Record 11 of Set 13 | barhi
Processing Record 12 of Set 13 | kutum
Processing Record 13 of Set 13 | koksovyy
Processing Record 14 of Set 13 | balikpapan
-------------------------------------
Data Retrieval Complete
-------------------------------------

In [8]:
city_weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,carnarvon,-24.87,113.63,284.15,100,17,3.1,AU,1597699336
1,korla,41.76,86.15,299.82,45,49,2.24,CN,1597699336
2,qaanaaq,77.48,-69.36,278.81,62,100,3.12,GL,1597699336
3,okato,-39.2,173.88,285.37,58,92,2.68,NZ,1597699336
4,kahului,20.89,-156.47,304.15,48,20,9.8,US,1597699337
...,...,...,...,...,...,...,...,...,...
609,borovoy,55.43,86.08,290.15,93,69,2,RU,1597699422
610,barhi,23.9,80.8,297.96,95,100,5.22,IN,1597699147
611,kutum,14.2,24.67,293.75,86,99,6.16,SD,1597699422
612,koksovyy,48.2,40.6,293.56,58,0,2.04,RU,1597699422
613,balikpapan,-1.27,116.83,297.96,89,100,2.65,ID,1597699423

In [9]:
# convert columns to appropriate format, and convert Max Temp from Kelvin to Fahrenheit

city_weather['Lat'] = pd.to_numeric(city_weather['Lat'])
city_weather['Lng'] = pd.to_numeric(city_weather['Lng'])
city_weather['Max Temp'] = pd.to_numeric(city_weather['Max Temp'])
city_weather['Max Temp'] = (((city_weather['Max Temp'] - 273.15) * (9/5)) + 32)
city_weather['Humidity'] = pd.to_numeric(city_weather['Humidity'])
city_weather['Cloudiness'] = pd.to_numeric(city_weather['Cloudiness'])
city_weather['Wind Speed'] = pd.to_numeric(city_weather['Wind Speed'])
city_weather['Date'] = pd.to_datetime(city_weather['Date'], unit = 's')

## Inspect the data and remove the cities where the humidity > 100%.
----
Skip this step if there are no cities that have humidity > 100%.

In [10]:
city_weather.head(20)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,carnarvon,-24.87,113.63,51.800,100.0,17.0,3.10,AU,2020-08-17 21:22:16
1,korla,41.76,86.15,80.006,45.0,49.0,2.24,CN,2020-08-17 21:22:16
2,qaanaaq,77.48,-69.36,42.188,62.0,100.0,3.12,GL,2020-08-17 21:22:16
3,okato,-39.20,173.88,53.996,58.0,92.0,2.68,NZ,2020-08-17 21:22:16
4,kahului,20.89,-156.47,87.800,48.0,20.0,9.80,US,2020-08-17 21:22:17
5,kapaa,22.08,-159.32,84.200,62.0,20.0,6.70,US,2020-08-17 21:20:25
6,arraial do cabo,-22.97,-42.03,75.200,88.0,98.0,1.50,BR,2020-08-17 21:22:17
7,ushuaia,-54.80,-68.30,33.800,86.0,75.0,5.10,AR,2020-08-17 21:22:17
8,saint george,37.10,-113.58,111.002,6.0,1.0,1.50,US,2020-08-17 21:19:45
9,adrar,20.50,-10.07,102.992,20.0,0.0,5.95,MR,2020-08-17 21:22:17
10,jamestown,42.10,-79.24,73.004,64.0,90.0,4.10,US,2020-08-17 21:22:17
11,saleaula,NaN,NaN,NaN,NaN,NaN,NaN,,NaT
12,avarua,-21.21,-159.78,73.400,64.0,5.0,4.10,CK,2020-08-17 21:22:18
13,dikson,73.51,80.55,50.468,92.0,68.0,6.08,RU,2020-08-17 21:22:18
14,hasaki,35.73,140.83,80.600,94.0,75.0,3.60,JP,2020-08-17 21:22:18
15,norman wells,65.28,-126.83,59.000,58.0,75.0,5.10,CA,2020-08-17 21:22:18
16,mar del plata,-38.00,-57.56,59.000,44.0,0.0,5.70,AR,2020-08-17 21:20:11
17,baykit,61.67,96.37,54.104,64.0,100.0,1.24,RU,2020-08-17 21:22:18
18,kulu,39.10,33.08,62.510,34.0,0.0,2.59,TR,2020-08-17 21:22:18
19,moscow,55.75,37.62,62.996,77.0,0.0,1.00,RU,2020-08-17 21:21:44

In [ ]:
#city_weather['Date'] = pd.to_datetime(city_weather['Date']).dt.date

In [ ]:
#city_weather.head(10)

In [11]:
city_weather['Date'] = pd.to_datetime(city_weather['Date'])
city_weather['Date'] = city_weather['Date'].dt.strftime('%m-%d-%Y')

In [12]:
city_weather.head(20)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,carnarvon,-24.87,113.63,51.800,100.0,17.0,3.10,AU,08-17-2020
1,korla,41.76,86.15,80.006,45.0,49.0,2.24,CN,08-17-2020
2,qaanaaq,77.48,-69.36,42.188,62.0,100.0,3.12,GL,08-17-2020
3,okato,-39.20,173.88,53.996,58.0,92.0,2.68,NZ,08-17-2020
4,kahului,20.89,-156.47,87.800,48.0,20.0,9.80,US,08-17-2020
5,kapaa,22.08,-159.32,84.200,62.0,20.0,6.70,US,08-17-2020
6,arraial do cabo,-22.97,-42.03,75.200,88.0,98.0,1.50,BR,08-17-2020
7,ushuaia,-54.80,-68.30,33.800,86.0,75.0,5.10,AR,08-17-2020
8,saint george,37.10,-113.58,111.002,6.0,1.0,1.50,US,08-17-2020
9,adrar,20.50,-10.07,102.992,20.0,0.0,5.95,MR,08-17-2020
10,jamestown,42.10,-79.24,73.004,64.0,90.0,4.10,US,08-17-2020
11,saleaula,NaN,NaN,NaN,NaN,NaN,NaN,,NaN
12,avarua,-21.21,-159.78,73.400,64.0,5.0,4.10,CK,08-17-2020
13,dikson,73.51,80.55,50.468,92.0,68.0,6.08,RU,08-17-2020
14,hasaki,35.73,140.83,80.600,94.0,75.0,3.60,JP,08-17-2020
15,norman wells,65.28,-126.83,59.000,58.0,75.0,5.10,CA,08-17-2020
16,mar del plata,-38.00,-57.56,59.000,44.0,0.0,5.70,AR,08-17-2020
17,baykit,61.67,96.37,54.104,64.0,100.0,1.24,RU,08-17-2020
18,kulu,39.10,33.08,62.510,34.0,0.0,2.59,TR,08-17-2020
19,moscow,55.75,37.62,62.996,77.0,0.0,1.00,RU,08-17-2020

In [14]:
len(city_weather['City'])

614

In [17]:
# Remove blank rows and save to csv

city_weather_clean = city_weather.dropna(how = 'any')
city_weather_clean.to_csv("city_weather_clean.csv")

#check length
len(city_weather_clean['City'])

568

In [19]:
Humidity_over_100 = city_weather_clean.loc[city_weather_clean['Humidity'] > 100]

Humidity_over_100.head()

Empty DataFrame
Columns: [City, Lat, Lng, Max Temp, Humidity, Cloudiness, Wind Speed, Country, Date]
Index: []

In [ ]:
#  Get the indices of cities that have humidity over 100%.
# Rows of cities that are over 100% humidity, city name.

In [ ]:
# Make a new DataFrame equal to the city data to drop all humidity outliers by index.
# Passing "inplace=False" will make a copy of the city_data DataFrame, which we call "clean_city_data".

In [ ]:
# Extract relevant fields from the data frame


# Export the City_Data into a csv

## Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

## Latitude vs. Temperature Plot

## Latitude vs. Humidity Plot

## Latitude vs. Cloudiness Plot

## Latitude vs. Wind Speed Plot

## Linear Regression

In [ ]:
# OPTIONAL: Create a function to create Linear Regression plots

In [ ]:
# Create Northern and Southern Hemisphere DataFrames

####  Northern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Southern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Northern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression

####  Southern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression